project:
  type: website
  
website:
  title: "Seth Watts"
  description: "Personal website of Seth Watts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- href: about.qmd
      - href: research.qmd
      - href: cv/swatts-cv.pdf
        text: CV
format: 
  html:
    theme: lux
    toc: true
  
  
  