project:
  type: website
  
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
  
website:
  title: "Seth Watts"
  description: "Personal website of Seth Watts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- href: about.qmd
      #- href: "research/index.qmd"
      #- text: "Research"
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: cv2/cv2.qmd
        text: CV
    right: 
      - icon: github
    
format: 
  html:
    css: styles.css
    theme: cosmo
    fontsize: 0.95em
    linestretch: 1.6
    code-style: solarized-dark
    toc: true
  
  
  