project:
  type: website
  output-dir: _site
  
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
  
website:
  title: "Seth Watts"
  description: "Personal website of Seth Watts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      #- href: about.qmd
      #- href: "research/index.qmd"
      #- text: "Research"
      - href: research.qmd
        text: Research
      - href: cv2/cv2.qmd
        text: CV
format: 
  html:
    theme: cosmo
    fontsize: 0.9em
    linestretch: 1.7
    toc: true
  
  
  